// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package api

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	_ "google.golang.org/genproto/googleapis/api"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	// _ "google/api"
)


// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Request struct {
	Message              string   `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Reply struct {
	Message              string   `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message,omitempty"`
	Count                int64    `protobuf:"zigzag64,2,opt,name=Count,proto3" json:"Count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Reply) Reset()         { *m = Reply{} }
func (m *Reply) String() string { return proto.CompactTextString(m) }
func (*Reply) ProtoMessage()    {}
func (*Reply) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{1}
}

func (m *Reply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Reply.Unmarshal(m, b)
}
func (m *Reply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Reply.Marshal(b, m, deterministic)
}
func (m *Reply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Reply.Merge(m, src)
}
func (m *Reply) XXX_Size() int {
	return xxx_messageInfo_Reply.Size(m)
}
func (m *Reply) XXX_DiscardUnknown() {
	xxx_messageInfo_Reply.DiscardUnknown(m)
}

var xxx_messageInfo_Reply proto.InternalMessageInfo

func (m *Reply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Reply) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type UserT struct {
	Uid                  int64    `protobuf:"zigzag64,1,opt,name=Uid,proto3" json:"Uid,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Sex                  int64    `protobuf:"zigzag64,3,opt,name=Sex,proto3" json:"Sex,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserT) Reset()         { *m = UserT{} }
func (m *UserT) String() string { return proto.CompactTextString(m) }
func (*UserT) ProtoMessage()    {}
func (*UserT) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{2}
}

func (m *UserT) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserT.Unmarshal(m, b)
}
func (m *UserT) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserT.Marshal(b, m, deterministic)
}
func (m *UserT) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserT.Merge(m, src)
}
func (m *UserT) XXX_Size() int {
	return xxx_messageInfo_UserT.Size(m)
}
func (m *UserT) XXX_DiscardUnknown() {
	xxx_messageInfo_UserT.DiscardUnknown(m)
}

var xxx_messageInfo_UserT proto.InternalMessageInfo

func (m *UserT) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *UserT) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UserT) GetSex() int64 {
	if m != nil {
		return m.Sex
	}
	return 0
}

type UidT struct {
	Uid                  int64    `protobuf:"zigzag64,1,opt,name=Uid,proto3" json:"Uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UidT) Reset()         { *m = UidT{} }
func (m *UidT) String() string { return proto.CompactTextString(m) }
func (*UidT) ProtoMessage()    {}
func (*UidT) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{3}
}

func (m *UidT) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UidT.Unmarshal(m, b)
}
func (m *UidT) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UidT.Marshal(b, m, deterministic)
}
func (m *UidT) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UidT.Merge(m, src)
}
func (m *UidT) XXX_Size() int {
	return xxx_messageInfo_UidT.Size(m)
}
func (m *UidT) XXX_DiscardUnknown() {
	xxx_messageInfo_UidT.DiscardUnknown(m)
}

var xxx_messageInfo_UidT proto.InternalMessageInfo

func (m *UidT) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func init() {
	proto.RegisterType((*Request)(nil), "service.goms.Request")
	proto.RegisterType((*Reply)(nil), "service.goms.Reply")
	proto.RegisterType((*UserT)(nil), "service.goms.UserT")
	proto.RegisterType((*UidT)(nil), "service.goms.UidT")
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_00212fb1f9d3bf1c) }

var fileDescriptor_00212fb1f9d3bf1c = []byte{
	// 337 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x91, 0x4f, 0x4b, 0xf3, 0x40,
	0x10, 0xc6, 0xfb, 0x27, 0x79, 0xdb, 0x0e, 0xef, 0xa1, 0xcc, 0xfb, 0x87, 0x10, 0x3d, 0x94, 0xf5,
	0xd2, 0x53, 0x82, 0x8a, 0x14, 0xf4, 0x20, 0xd8, 0x7a, 0x54, 0x24, 0x6d, 0x2e, 0xde, 0xb6, 0x66,
	0x0c, 0x0b, 0x69, 0x76, 0xcd, 0x6e, 0x4b, 0x7b, 0xf5, 0x2b, 0xf8, 0x59, 0xfc, 0x24, 0x7e, 0x05,
	0x3f, 0x88, 0x64, 0xd3, 0x82, 0x94, 0xd4, 0xdb, 0xce, 0xcc, 0xf3, 0x7b, 0x86, 0xd9, 0x07, 0x7a,
	0x5c, 0x89, 0x40, 0x15, 0xd2, 0x48, 0xfc, 0xad, 0xa9, 0x58, 0x89, 0x27, 0x0a, 0x52, 0xb9, 0xd0,
	0xfe, 0x71, 0x2a, 0x65, 0x9a, 0x51, 0xc8, 0x95, 0x08, 0x79, 0x9e, 0x4b, 0xc3, 0x8d, 0x90, 0xb9,
	0xae, 0xb4, 0xfe, 0xd1, 0x76, 0x6a, 0xab, 0xf9, 0xf2, 0x39, 0xa4, 0x85, 0x32, 0x9b, 0x6a, 0xc8,
	0x4e, 0xa0, 0x13, 0xd1, 0xcb, 0x92, 0xb4, 0x41, 0x0f, 0x3a, 0x77, 0xa4, 0x35, 0x4f, 0xc9, 0x6b,
	0x0e, 0x9a, 0xc3, 0x5e, 0xb4, 0x2b, 0xd9, 0x08, 0xdc, 0x88, 0x54, 0xb6, 0x39, 0x2c, 0xc1, 0xbf,
	0xe0, 0x8e, 0xe5, 0x32, 0x37, 0x5e, 0x6b, 0xd0, 0x1c, 0x62, 0x54, 0x15, 0xec, 0x1a, 0xdc, 0x58,
	0x53, 0x31, 0xc3, 0x3e, 0xb4, 0x63, 0x91, 0x58, 0x08, 0xa3, 0xf2, 0x89, 0x08, 0xce, 0x3d, 0x5f,
	0x90, 0xd5, 0xf7, 0x22, 0xfb, 0x2e, 0x55, 0x53, 0x5a, 0x7b, 0xed, 0x4a, 0x35, 0xa5, 0x35, 0xf3,
	0xc0, 0x89, 0x45, 0x52, 0xc3, 0x9f, 0xbd, 0xb7, 0xc0, 0x29, 0xbd, 0x71, 0x02, 0xce, 0x83, 0xc8,
	0x53, 0xfc, 0x17, 0x7c, 0xff, 0x93, 0x60, 0x7b, 0x95, 0xff, 0x67, 0xbf, 0xad, 0xb2, 0x0d, 0xeb,
	0xbf, 0x7e, 0x7c, 0xbe, 0xb5, 0x00, 0xbb, 0xe1, 0xea, 0x34, 0x54, 0x25, 0x3d, 0x02, 0x18, 0x17,
	0xc4, 0x0d, 0x59, 0xcf, 0x3d, 0xc8, 0xde, 0xe0, 0xe3, 0x5e, 0x53, 0x24, 0x33, 0xd6, 0xc0, 0x2b,
	0x80, 0x58, 0x25, 0x3f, 0x82, 0xff, 0x83, 0x2a, 0x81, 0x60, 0x97, 0x40, 0x70, 0x5b, 0x26, 0xc0,
	0x1a, 0x78, 0x01, 0xdd, 0x88, 0x78, 0x62, 0xd1, 0x1a, 0x7b, 0xbf, 0xce, 0x8e, 0x35, 0xf0, 0x12,
	0x60, 0x42, 0x19, 0x6d, 0x77, 0xd6, 0x81, 0x07, 0x57, 0xde, 0xb8, 0x8f, 0x6d, 0xae, 0xc4, 0xfc,
	0x97, 0x1d, 0x9c, 0x7f, 0x05, 0x00, 0x00, 0xff, 0xff, 0x8c, 0xb7, 0xbc, 0xe1, 0x54, 0x02, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserClient is the client API for User service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserClient interface {
	Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Reply, error)
	CreateUser(ctx context.Context, in *UserT, opts ...grpc.CallOption) (*UidT, error)
	UpdateUser(ctx context.Context, in *UserT, opts ...grpc.CallOption) (*empty.Empty, error)
	ReadUser(ctx context.Context, in *UidT, opts ...grpc.CallOption) (*UserT, error)
	DeleteUser(ctx context.Context, in *UidT, opts ...grpc.CallOption) (*empty.Empty, error)
}

type userClient struct {
	cc *grpc.ClientConn
}

func NewUserClient(cc *grpc.ClientConn) UserClient {
	return &userClient{cc}
}

func (c *userClient) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Reply, error) {
	out := new(Reply)
	err := c.cc.Invoke(ctx, "/service.goms.User/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) CreateUser(ctx context.Context, in *UserT, opts ...grpc.CallOption) (*UidT, error) {
	out := new(UidT)
	err := c.cc.Invoke(ctx, "/service.goms.User/CreateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) UpdateUser(ctx context.Context, in *UserT, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/service.goms.User/UpdateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) ReadUser(ctx context.Context, in *UidT, opts ...grpc.CallOption) (*UserT, error) {
	out := new(UserT)
	err := c.cc.Invoke(ctx, "/service.goms.User/ReadUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) DeleteUser(ctx context.Context, in *UidT, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/service.goms.User/DeleteUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServer is the server API for User service.
type UserServer interface {
	Ping(context.Context, *Request) (*Reply, error)
	CreateUser(context.Context, *UserT) (*UidT, error)
	UpdateUser(context.Context, *UserT) (*empty.Empty, error)
	ReadUser(context.Context, *UidT) (*UserT, error)
	DeleteUser(context.Context, *UidT) (*empty.Empty, error)
}

// UnimplementedUserServer can be embedded to have forward compatible implementations.
type UnimplementedUserServer struct {
}

func (*UnimplementedUserServer) Ping(ctx context.Context, req *Request) (*Reply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (*UnimplementedUserServer) CreateUser(ctx context.Context, req *UserT) (*UidT, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUser not implemented")
}
func (*UnimplementedUserServer) UpdateUser(ctx context.Context, req *UserT) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUser not implemented")
}
func (*UnimplementedUserServer) ReadUser(ctx context.Context, req *UidT) (*UserT, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadUser not implemented")
}
func (*UnimplementedUserServer) DeleteUser(ctx context.Context, req *UidT) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteUser not implemented")
}

func RegisterUserServer(s *grpc.Server, srv UserServer) {
	s.RegisterService(&_User_serviceDesc, srv)
}

func _User_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.goms.User/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).Ping(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserT)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.goms.User/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).CreateUser(ctx, req.(*UserT))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_UpdateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserT)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).UpdateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.goms.User/UpdateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).UpdateUser(ctx, req.(*UserT))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_ReadUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UidT)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).ReadUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.goms.User/ReadUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).ReadUser(ctx, req.(*UidT))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_DeleteUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UidT)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).DeleteUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.goms.User/DeleteUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).DeleteUser(ctx, req.(*UidT))
	}
	return interceptor(ctx, in, info, handler)
}

var _User_serviceDesc = grpc.ServiceDesc{
	ServiceName: "service.goms.User",
	HandlerType: (*UserServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _User_Ping_Handler,
		},
		{
			MethodName: "CreateUser",
			Handler:    _User_CreateUser_Handler,
		},
		{
			MethodName: "UpdateUser",
			Handler:    _User_UpdateUser_Handler,
		},
		{
			MethodName: "ReadUser",
			Handler:    _User_ReadUser_Handler,
		},
		{
			MethodName: "DeleteUser",
			Handler:    _User_DeleteUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}
