FROM ubuntu       
RUN apt-get update -y
RUN groupadd -r gConf && useradd -r -g gConf uConf
USER uConf
RUN ["pwd"]
WORKDIR /home/uConf
COPY ./docker/eConf ./              
COPY ./configs ./configs
RUN ["ls","-l","./eConf"]         
RUN ["ls","-l","./configs/"]         
CMD ["./eConf","-confpath=./configs"]