FROM mysql:8.0

# 免密登录
ENV MYSQL_ALLOW_EMPTY_PASSWORD true

# 必须同时设置用户名(拥有特权)、密码和数据库
# ENV MYSQL_USER utest
# ENV MYSQL_PASSWORD pwtest
# ENV MYSQL_DATABASE test_db

# 复制文件
WORKDIR /docker-entrypoint-initdb.d
COPY ./setup/mysql/test_db ./test_db
COPY ./setup/mysql/user ./user
COPY ./setup/mysql/setup.sh  ./setup.sh 

# 启动命令
# CMD ["sh", "/mysql/setup.sh"]

