FROM ubuntu       
RUN apt-get update -y
RUN groupadd -r gConf && useradd -r -g gConf uConf
USER uConf
RUN ["pwd"]
WORKDIR /home/uConf
COPY ./docker/eMysql ./              
COPY ./configs ./configs
RUN ["ls","-l","./eMysql"]         
RUN ["ls","-l","./configs/"]         
CMD ["./eMysql","-confpath=./configs"]