FROM alpine:latest
LABEL maintainer="sfuwen@sina.com"
# 安装
RUN apk update && apk upgrade && apk add bash curl
RUN wget https://github.com/fullstorydev/grpcurl/releases/download/v1.6.0/grpcurl_1.6.0_linux_x86_64.tar.gz \
    && tar -C /usr/local/bin -xvf grpcurl_1.6.0_linux_x86_64.tar.gz \
    && rm grpcurl_1.6.0_linux_x86_64.tar.gz
