FROM ubuntu       
RUN apt-get update -y
RUN groupadd -r gYaml && useradd -r -g gYaml uYaml
USER uYaml
RUN ["pwd"]
WORKDIR /home/uYaml
COPY ./docker/eYaml ./              
COPY ./configs ./configs
RUN ["ls","-l","./eYaml"]         
RUN ["ls","-l","./configs/"]         
CMD ["./eYaml"]