FROM ubuntu       
RUN apt-get update -y
RUN groupadd -r gFlag && useradd -r -g gFlag uFlag
USER uFlag
RUN ["pwd"]
WORKDIR /home/uFlag
COPY ./docker/eFlag ./              
COPY ./configs ./configs
RUN ["ls","-l","./eFlag"]         
RUN ["ls","-l","./configs/"]         
CMD ["./eFlag","-s=string","-i=1","-bool=true","xx","yy","zz"]