FROM mysql:5.7
USER root
ENV MYSQL_ALLOW_EMPTY_PASSWORD yes
# ENV MYSQL_ROOT_PASSWORD root
# RUN apt-get update -y
# RUN apt-get install mysql-server
COPY ./sql  /sql
COPY ./bash /bash
COPY ./container/mysqltest_v3/init.sh /
# COPY ./container/mysqltest_v3/.my.cnf /root/.my.cnf
RUN ls -l /bash/ /init.sh
RUN chmod +x /bash
RUN chmod +x /init.sh
# RUN chmod 644 /root/.my.cnf
# RUN chmod 777 /root/.my.cnf
RUN ls -l /bash/ /init.sh
RUN cat /init.sh
CMD ["sh","/init.sh"]