FROM mysql:8.0
LABEL maintainer="sfuwen@sina.com"
# root 免密登录
ENV MYSQL_ALLOW_EMPTY_PASSWORD true

# 必须同时设置用户名(拥有特权)、密码和数据库
# ENV MYSQL_USER utest
# ENV MYSQL_PASSWORD pwtest
# ENV MYSQL_DATABASE test_db

# 复制文件
WORKDIR /docker-entrypoint-initdb.d
COPY ./setup/test_db ./test_db
COPY ./setup/user ./user
COPY ./setup/setup-data.sh  ./setup-data.sh

# 启动命令
# CMD ["sh", "/mysql/setup.sh"]
